print('hello'.isalpha())
print('hello123'.isalpha())
print('hello123'.isalnum())
print('hello'.isalnum())
print('123'.isdecimal())
print('    '.isspace())
print('This Is Title Case'.istitle())
print('This Is Title Cased 123'.istitle())
print('This Is not Title Case'.istitle())
print('This Is NOT Title Case Either')